---
services:
  whiterose:
    image: fabianoflorentino/whiterose:v0.0.1
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/whiterose
    tty: true
    stdin_open: true
    healthcheck:
      test: ["CMD-SHELL", "ps aux |grep 'air' || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
