package update

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/fabianoflorentino/whiterose/internal/domain/entities"
)

type UpdateService struct {
	prBase string
}

func New() *UpdateService {
	return &UpdateService{prBase: "main"}
}

func (s *UpdateService) SetPRBase(base string) {
	s.prBase = base
}

func (s *UpdateService) UpdateGoMod(project entities.UpdateProject, strategy entities.UpdateStrategy, major bool) error {
	projectPath := project.Path
	if !filepath.IsAbs(projectPath) {
		projectPath = filepath.Join(project.Path)
	}

	goModPath := filepath.Join(projectPath, "go.mod")
	if _, err := os.Stat(goModPath); err != nil {
		return fmt.Errorf("go.mod not found in %s: %w", projectPath, err)
	}

	currentVersion := s.getCurrentGoVersion(goModPath)
	newVersion := s.calculateNewVersion(currentVersion, strategy, major)

	if err := s.updateGoModFile(goModPath, newVersion); err != nil {
		return fmt.Errorf("failed to update go.mod: %w", err)
	}

	if err := s.runGoModTidy(projectPath); err != nil {
		return fmt.Errorf("failed to run go mod tidy: %w", err)
	}

	fmt.Printf("Updated go.mod in %s: %s -> %s\n", project.Name, currentVersion, newVersion)
	return nil
}

func (s *UpdateService) UpdateGoVersion(project entities.UpdateProject, strategy entities.UpdateStrategy, major bool) error {
	projectPath := project.Path
	goModPath := filepath.Join(projectPath, "go.mod")

	currentVersion := s.getCurrentGoVersion(goModPath)
	newVersion := s.calculateNewVersion(currentVersion, strategy, major)

	if err := s.updateGoModFile(goModPath, newVersion); err != nil {
		return fmt.Errorf("failed to update Go version in go.mod: %w", err)
	}

	fmt.Printf("Updated Go version in %s: %s -> %s\n", project.Name, currentVersion, newVersion)
	return nil
}

func (s *UpdateService) UpdateDockerImage(project entities.UpdateProject, strategy entities.UpdateStrategy, major bool) error {
	projectPath := project.Path
	dockerfilePath := filepath.Join(projectPath, "Dockerfile")

	content, err := os.ReadFile(dockerfilePath)
	if err != nil {
		return fmt.Errorf("failed to read Dockerfile: %w", err)
	}

	currentImage := s.extractDockerImage(string(content))
	if currentImage == "" {
		return fmt.Errorf("could not find base image in Dockerfile")
	}

	newImage := s.calculateNewDockerImage(currentImage, strategy, major)

	newContent := strings.Replace(string(content), currentImage, newImage, 1)
	if err := os.WriteFile(dockerfilePath, []byte(newContent), 0644); err != nil {
		return fmt.Errorf("failed to write Dockerfile: %w", err)
	}

	fmt.Printf("Updated Docker image in %s: %s -> %s\n", project.Name, currentImage, newImage)
	return nil
}

func (s *UpdateService) CreateBranchAndCommit(project entities.UpdateProject, changes []string) (string, error) {
	projectPath := project.Path

	origDir, _ := os.Getwd()
	defer os.Chdir(origDir)

	if err := os.Chdir(projectPath); err != nil {
		return "", fmt.Errorf("failed to change to project directory: %w", err)
	}

	branchName := "update/" + entities.GetTimestampedBranchName()

	cmd := exec.Command("git", "checkout", "-b", branchName)
	if out, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("failed to create branch %s: %w\n%s", branchName, err, out)
	}

	cmd = exec.Command("git", "add", ".")
	if out, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("git add failed: %w\n%s", err, out)
	}

	commitMsg := "chore: update dependencies\n\n" + strings.Join(changes, "\n")
	cmd = exec.Command("git", "commit", "-m", commitMsg)
	if out, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("git commit failed: %w\n%s", err, out)
	}

	fmt.Printf("Created branch %s with commit\n", branchName)

	cmd = exec.Command("git", "push", "origin", branchName)
	if out, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("git push failed: %w\n%s", err, out)
	}

	fmt.Printf("Pushed branch %s to origin\n", branchName)
	return branchName, nil
}

func (s *UpdateService) CreatePR(project entities.UpdateProject, branchName string, changes []string) error {
	return s.CreatePRWithBase(project, branchName, changes, s.prBase)
}

func (s *UpdateService) CreatePRWithBase(project entities.UpdateProject, branchName string, changes []string, base string) error {
	cmd := exec.Command("gh", "pr", "create",
		"--title", fmt.Sprintf("chore: update dependencies in %s", project.Name),
		"--body", fmt.Sprintf("## Summary\n- %s\n\nAuto-generated by whiterose update command.", strings.Join(changes, "\n- ")),
		"--base", base,
	)

	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to create PR: %w\n%s", err, out)
	}

	fmt.Printf("PR created: %s\n", strings.TrimSpace(string(out)))
	return nil
}

func (s *UpdateService) LoadUpdateConfig(configPath string) ([]entities.UpdateProject, error) {
	data, err := os.ReadFile(configPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read config: %w", err)
	}

	return entities.ParseUpdateConfig(data)
}

func (s *UpdateService) getCurrentGoVersion(goModPath string) string {
	content, _ := os.ReadFile(goModPath)
	lines := strings.Split(string(content), "\n")
	for _, line := range lines {
		if strings.HasPrefix(line, "go ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "go "))
		}
	}
	return ""
}

func (s *UpdateService) calculateNewVersion(current string, strategy entities.UpdateStrategy, major bool) string {
	if current == "" {
		return "1.25.0"
	}

	parts := strings.Split(current, ".")
	if len(parts) < 3 {
		return "1.25.0"
	}

	majorNum := 0
	minorNum := 0
	patchNum := 0
	fmt.Sscanf(current, "%d.%d.%d", &majorNum, &minorNum, &patchNum)

	if major {
		majorNum++
		minorNum = 0
		patchNum = 0
	} else if strategy == entities.StrategyMajor {
		majorNum++
		minorNum = 0
		patchNum = 0
	} else if strategy == entities.StrategyMinor {
		minorNum++
		patchNum = 0
	} else {
		patchNum++
	}

	goVersion := fmt.Sprintf("%d.%d.%d", majorNum, minorNum, patchNum)
	if major || strategy == entities.StrategyMajor {
		goVersion += "-rc.1"
	}
	return goVersion
}

func (s *UpdateService) extractDockerImage(dockerfile string) string {
	lines := strings.Split(dockerfile, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "FROM ") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				return parts[1]
			}
		}
	}
	return ""
}

func (s *UpdateService) calculateNewDockerImage(current string, strategy entities.UpdateStrategy, major bool) string {
	parts := strings.Split(current, ":")
	if len(parts) != 2 {
		return current
	}

	image := parts[0]
	version := parts[1]

	versionParts := strings.Split(version, "-")
	baseVersion := versionParts[0]

	numParts := strings.Split(baseVersion, ".")
	if len(numParts) < 2 {
		return current
	}

	majorNum := 0
	minorNum := 0
	fmt.Sscanf(baseVersion, "%d.%d", &majorNum, &minorNum)

	if major {
		majorNum++
		minorNum = 0
	} else if strategy == entities.StrategyMajor {
		majorNum++
		minorNum = 0
	} else if strategy == entities.StrategyMinor {
		minorNum++
	}

	newVersion := fmt.Sprintf("%d.%d", majorNum, minorNum)
	if len(versionParts) > 1 {
		newVersion += "-" + versionParts[1]
	}

	return image + ":" + newVersion
}

func (s *UpdateService) updateGoModFile(path string, version string) error {
	content, err := os.ReadFile(path)
	if err != nil {
		return err
	}

	lines := strings.Split(string(content), "\n")
	newLines := make([]string, 0)
	for _, line := range lines {
		if strings.HasPrefix(line, "go ") {
			newLines = append(newLines, "go "+version)
		} else {
			newLines = append(newLines, line)
		}
	}

	return os.WriteFile(path, []byte(strings.Join(newLines, "\n")), 0644)
}

func (s *UpdateService) runGoModTidy(projectPath string) error {
	cmd := exec.Command("go", "mod", "tidy")
	cmd.Dir = projectPath
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("%w: %s", err, out)
	}
	return nil
}